SUCCESS = 1
FAILURE = 0

USER_NOT_FOUND = 41
PASSWORD_WRONG = 42

USER_ALREADY_EXIST = 51

LOCATION_DESCRIPTION_SERVICE_UNAVAILABLE = 81

POST_CIPHER_WRONG = 111

code_desc = {
    USER_NOT_FOUND: "User is not found",
    PASSWORD_WRONG: "Password is wrong",
    USER_ALREADY_EXIST: "User already exists",
    LOCATION_DESCRIPTION_SERVICE_UNAVAILABLE: "Location description is not available",
    POST_CIPHER_WRONG: "Wrong cipher",
}

